[package]
name = "socky-be"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async
tokio = { version = "1.49.0", features = ["full"] }
async-trait = "0.1.79"
# Web
axum = "0.8.8"
tower-cookies = "0.11.0"
tower-http = { version = "0.6.8", features = ["fs"] }
# Json
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.149"
serde_with = "3.7.0"
# Model
rust_decimal = "1.39.0"
# Tracing
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
# Others
lazy-regex = "3.5.1"
strum_macros = "0.27.2"
uuid = { version = "1.19.0", features = ["v4","fast-rng"] }

[dev-dependencies]
anyhow = "1.0.81"
httpc-test = "0.1.9"
